### ISSUE TITLE
Migrate following endpoints to the new cache system.

### ISSUE THREAD

**Issue by andreespirela** [useverto/interface#7]
1) From now on, we won't be making direct calls to the cache system, instead, we will be using https://github.com/useverto/cace-interface with NPM by running `npm install verto-cace-interface`. Check the _README_ of the repo for more information.

1) Migrate the following lines:

- [x]  https://github.com/useverto/interface/blob/main/src/pages/space/%5Bid%5D.tsx#L42. ---------> https://github.com/useverto/cace-interface#fetching-token-metadata

- [x] https://github.com/useverto/interface/blob/main/src/pages/space/%5Bid%5D.tsx#L53 --------->  https://github.com/useverto/cace-interface#fetching-a-single-collection-by-collection-id 

- [x] https://github.com/useverto/interface/blob/main/src/pages/user/%5Binput%5D/creations.tsx#L31 ---------> https://github.com/useverto/cache-interface#fetching-all-creations-art-given-a-username **[*]**

- [x] https://github.com/useverto/interface/blob/main/src/pages/user/%5Binput%5D/owns.tsx#L31 ---------> https://github.com/useverto/cache-interface#fetching-all-the-balances-for-a-given-username

- [x] https://github.com/useverto/interface/blob/main/src/pages/app.tsx#L74 ---------> https://github.com/useverto/cache-interface#fetching-all-the-balances-for-a-given-username

- [x] https://github.com/useverto/interface/blob/main/src/pages/api/token_og.ts#L32 ---------> https://github.com/useverto/cache-interface#fetching-a-contract 

- [x] https://github.com/useverto/interface/blob/main/src/pages/user/%5Binput%5D.tsx#L98 ---------> https://github.com/useverto/cache-interface#fetching-all-creations-art-given-a-username

- [x] https://github.com/useverto/interface/blob/main/src/pages/user/%5Binput%5D.tsx#L106 ---------> https://github.com/useverto/cache-interface#fetching-all-the-balances-for-a-given-username

- [x] https://github.com/useverto/interface/blob/main/src/components/space/Community.tsx#L44 ---------> https://github.com/useverto/cache-interface#fetching-a-contract

**Notes:**
- Pagination will need to be done on the user side, for example, **[*]** originally takes a length to be filtered. This needs to be done on the client side as `cache-interface` sends an absolute value for performance purposes.
- Some APIs can be either by username or user address. Be on the lookout for this.
- Please, let me know if something is missing.

**Comment by martonlederer** [comment]
Implemented :D
